### ISSUE TITLE
Getting an error on start.

### ISSUE THREAD

**Issue by Bazmundi** [eventB-Soton/Rodin-Bundles#4]
WIN64 version of latest bundle.  On windows 10.  

Does not start.

Displays an error complaining about a missing (unnamed) shared library.

**Comment by tshoang** [comment]
Thank you very much for the report. Can you please give us more information? The .log file in the .metadata folder of the workspace should contain some relevant information. Can you copy the content of the file here?

**Comment by tshoang** [comment]
Closed as there is no further information available.
